# Site settings
author: gj
title: The Sound and the Fury
header-img: img/home-bg.png
email: g.e.jensen@gmail.com
copyright_name: gj
description: > # this means to ignore newlines until "baseurl:"
  traveling back in time to find the future
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SoundandtheFury

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
